### ISSUE TITLE
I cannot connect but when I tried to ssh via powershell I can connect

### ISSUE THREAD

**Issue by njamortel** [ShellAssistant/ShellAssistant#1]
Custom crypto binding not available
Local ident: 'SSH-2.0-ssh2js1.5.0'
Client: Trying 10.28.65.201 on port 22 ...
Socket connected
Connected to socket on host: 10.28.65.201:22
Remote ident: 'SSH-2.0-OpenSSH_3.9p1'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
Handshake: No matching key exchange algorithm
Outbound: Sending DISCONNECT (3)
Handshake failed: no matching key exchange algorithm
Socket ended
Socket closed

**Comment by njamortel** [comment]
ok noted. How about a local powershell? this application is still not
detecting the powershell only the windows bash. Thank you very much!

[image: image.png]

**Comment by ShellAssistant** [comment]
Yes, Powershell is something that I would very much like to add. It will be supported eventually, but for scheduling reasons this might be a bit further down the road.

I have enabled the legacy ssh protocols with a security warning being displayed to the user on connection, recommending that they upgrade sshd on the server they are connecting to. I think this should be sufficient. It should be available in version 0.6.1, probably sometime next week. I'll let you know once it's available. Thanks very much for your feedback!

**Comment by ShellAssistant** [comment]
An update on the delay: Build 0.6.2 which contains this feature has been awaiting certification from the store for more than 2 days now which is much longer than usual. Not sure what the hold up is, but hopefully it shouldn't be too much longer. I'll update as soon as it goes live. Thank you very much for your patience!

**Comment by ShellAssistant** [comment]
Version 0.6.4 has just been certified and should now be available from:

Snap Store (Linux): [https://snapcraft.io/shell-assistant](https://snapcraft.io/shell-assistant)
Microsoft Store (Windows): [https://www.microsoft.com/store/apps/9NR2G5QKF1BK](https://www.microsoft.com/store/apps/9NR2G5QKF1BK)
Developer website (Mac, Linux, Windows): [https://shellassistant.com](https://shellassistant.com)

Apologies for the delay. I cancelled the earlier submission thinking it might have stalled and then resubmitted which may have taken longer in the long run.

Please let me know if this is fulfills for your needs so that the issue can be closed.

Thanks very much for your feedback! Please let me know if you have any further suggestions or comments.

**Comment by njamortel** [comment]
Yes it fulfills my need. Thank you very much.
