### ISSUE TITLE
Feature Request: allow user to rename terminal session tabs

### ISSUE THREAD

**Issue by 888JW** [ShellAssistant/ShellAssistant#2]
Would it be possible to allow the user to change the name displayed on the terminal session tabs? 
With multiple tabs open for the same connection it is difficult to know what each tab is because it currently displays the bash prompt. 
Otherwise, I am very impressed with the the features.
Thank you

**Comment by ShellAssistant** [comment]
That seems like a reasonable request.
I have implemented the above change, to allow the shell tab titles to be renamed.
This should be available in version 0.6.1 which I expect should be released within the next day or two if all goes well.
Thanks very much for your feedback!

**Comment by 888JW** [comment]
Awesome. Thanks for the quick response and for adding the feature.

**Comment by ShellAssistant** [comment]
An update on the delay: Build 0.6.2 which contains this feature has been awaiting certification from the store for more than 2 days now which is much longer than usual. Not sure what the hold up is, but hopefully it shouldn't be too much longer. I'll update as soon as it goes live. Thank you very much for your patience!

**Comment by ShellAssistant** [comment]
Version 0.6.4 has just been certified and should now be available from:

Snap Store (Linux): [https://snapcraft.io/shell-assistant](https://snapcraft.io/shell-assistant)
Microsoft Store (Windows): [https://www.microsoft.com/store/apps/9NR2G5QKF1BK](https://www.microsoft.com/store/apps/9NR2G5QKF1BK)
Developer website (Mac, Linux, Windows): [https://shellassistant.com](https://shellassistant.com)

Apologies for the delay. I cancelled the earlier submission thinking it might have stalled and then resubmitted which may have taken longer in the long run.

Please let me know if this is fulfills for your needs so that the issue can be closed.

Thanks very much for your feedback! Please let me know if you have any further suggestions or comments.

**Comment by 888JW** [comment]
Just downloaded and it looks/works great.  Exactly what I needed.
Thank you for responding so quickly to the feature request.

**Comment by rangerdude** [comment]
How does one rename the tab? Cant figure it out..
