### ISSUE TITLE
Workspaces was not saved

### ISSUE THREAD

**Issue by njamortel** [ShellAssistant/ShellAssistant#3]
The workspaces cannot be saved. Is it possible to add features to save the workspace?

**Comment by ShellAssistant** [comment]
Thanks very much for the feedback.

The code to save & load workspaces is already there, but it is not yet enabled. It would automatically login and start all the sessions that were open at the time the user saved or last exited the app. Only the sessions themselves are saved at present, though. The state of all the user interface components inside the sessions or the terminal contents aren't currently saved.

At the moment, it would automatically load & save when the application starts or exits, but I might change this to instead use manual Save/Load buttons on the Workspaces view. The feature also needs more testing.

Let me see if I can get this into the next upcoming release, otherwise it will be the release after that. I'll update again once I have a better idea when this should be available.

**Comment by ShellAssistant** [comment]
Thanks very much for filing this issue.
There has been no response from originator for some time, so I have self-verified this issue as being fixed and am closing the issue as resolved, as the developer.
